[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
dynamic_padding = false
opacity = 0.95
padding = { x = 0, y = 0 }
option_as_alt = "Both"
dimensions = { columns = 160, lines = 80 }
blur = true

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[cursor]
style = { shape = "Beam", blinking = "On" }

[font]
size = 22
normal = { family = "GeistMono Nerd Font Propo", style = "Regular" }
bold = { family = "GeistMono Nerd Font Propo", style = "Bold" }
italic = { family = "GeistMono Nerd Font Propo", style = "Italic" }
bold_italic = { family = "JetbrainsMono Nerd Font", style = "Bold Italic" }

[colors.primary]
background = "#24292e"
foreground = "#d1d5da"

[colors.normal]
black = "#000000"
red = "#ea4a5a"
green = "#34d058"
yellow = "#ffea7f"
blue = "#2188ff"
magenta = "#b392f0"
cyan = "#39c5cf"
white = "#ffffff"

[colors.bright]
black = "#959da5"
red = "#f97583"
green = "#85e89d"
yellow = "#ffea7f"
blue = "#79b8ff"
magenta = "#b392f0"
cyan = "#56d4dd"
white = "#ffffff"

[[colors.indexed_colors]]
index = 16
color = "#d18616"

[[colors.indexed_colors]]
index = 17
color = "#f97583"
