[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
dynamic_padding = false
opacity = 0.95
padding = { x = 0, y = 0 }
option_as_alt = "Both"
dimensions = { columns = 160, lines = 80 }
blur = true

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[cursor]
style = { shape = "Beam", blinking = "On" }

[font]
size = 22
normal = { family = "GeistMono Nerd Font Propo", style = "Regular" }
bold = { family = "GeistMono Nerd Font Propo", style = "Bold" }
italic = { family = "GeistMono Nerd Font Propo", style = "Italic" }
bold_italic = { family = "JetbrainsMono Nerd Font", style = "Bold Italic" }

[colors.primary]
background = "#181616"
foreground = "#c5c9c5"

[colors.normal]
black = "#0d0c0c"
red = "#c4746e"
green = "#8a9a7b"
yellow = "#c4b28a"
blue = "#8ba4b0"
magenta = "#a292a3"
cyan = "#8ea4a2"
white = "#c8c093"

[colors.bright]
black = "#a6a69c"
red = "#e46876"
green = "#87a987"
yellow = "#e6c384"
blue = "#7fb4ca"
magenta = "#938aa9"
cyan = "#7aa89f"
white = "#c5c9c5"

[colors.selection]
background = "#2d4f67"
foreground = "#c8c093"

[[colors.indexed_colors]]
index = 16
color = "#b6927b"

[[colors.indexed_colors]]
index = 17
color = "#b98d7b"
