[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
dynamic_padding = false
opacity = 0.95
padding = { x = 0, y = 0 }
option_as_alt = "Both"
dimensions = { columns = 160, lines = 100 }
blur = true

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[cursor]
style = { shape = "Beam", blinking = "On" }

[font]
size = 16
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

[colors]
primary = { background = "#191D24", foreground = "#D8DEE9" }
normal = { black = "#3B4252", red = "#BF616A", green = "#A3BE8C", yellow = "#EBCB8B", blue = "#81A1C1", magenta = "#B48EAD", cyan = "#88C0D0", white = "#E5E9F0" }
bright = { black = "#4C566A", red = "#D08770", green = "#A3BE8C", yellow = "#EBCB8B", blue = "#5E81AC", magenta = "#B48EAD", cyan = "#8FBCBB", white = "#ECEFF4" }
selection = { text = "#2E3440", background = "#D8DEE9" }
cursor = { text = "#2E3440", cursor = "#97B67C" }
