[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
dynamic_padding = false
opacity = 0.95
padding = { x = 0, y = 0 }
option_as_alt = "Both"
dimensions = { columns = 160, lines = 80 }
blur = true

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[cursor]
style = { shape = "Beam", blinking = "On" }

[font]
size = 22
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

[colors.primary]
background = "#101010"
foreground = "#ffffff"

[colors.normal]
black = "#101010"
red = "#f5a191"
green = "#90b99f"
yellow = "#e6b99d"
blue = "#aca1cf"
magenta = "#e29eca"
cyan = "#7fc8c6"
white = "#a0a0a0"

[colors.bright]
black = "#7e7e7e"
red = "#ff8080"
green = "#99ffe4"
yellow = "#ffc799"
blue = "#b9aeda"
magenta = "#ecaad6"
cyan = "#a9e3e1"
white = "#ffffff"
