general.import = ["~/.config/alacritty/theme.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
dynamic_padding = false
opacity = 0.95
padding = { x = 0, y = 0 }
option_as_alt = "Both"
dimensions = { columns = 160, lines = 80 }
blur = true

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[cursor]
style = { shape = "Beam", blinking = "On" }

[font]
size = 21
normal = { family = "GeistMono Nerd Font Propo", style = "Regular" }
bold = { family = "GeistMono Nerd Font Propo", style = "Bold" }
italic = { family = "GeistMono Nerd Font Propo", style = "Italic" }
bold_italic = { family = "JetbrainsMono Nerd Font", style = "Bold Italic" }
