[colors.primary]
foreground = "#adbac7"
background = "#1c2128"

[colors.cursor]
text = "#1c2128"
cursor = "#adbac7"

[colors.selection]
text = "#adbac7"
background = "#264f78"

[colors.normal]
black = "#545d68"
red = "#f47067"
green = "#57ab5a"
yellow = "#c69026"
blue = "#539bf5"
magenta = "#b083f0"
cyan = "#39c5cf"
white = "#909dab"

[colors.bright]
black = "#636e7b"
red = "#ff938a"
green = "#6bc46d"
yellow = "#daaa3f"
blue = "#6cb6ff"
magenta = "#dcbdfb"
cyan = "#56d4dd"
white = "#cdd9e5"
