add_newline = true
command_timeout = 700
scan_timeout = 30

format = """
ğŸ§‰ $os$username$hostname$directory$git_branch$git_state$git_status
$status$jobs$character
"""
right_format = "$cmd_duration$time$aws$docker_context$nix_shell$nodejs$bun$python$golang$rust$lua$c"

[username]
show_always = false
style_user = "bold"
style_root = "bold red"
format = "[$user]($style)"

[hostname]
ssh_only = true
trim_at = "."
style = "cyan"
format = "@[$hostname]($style) "

[os]
disabled = true
style = "black"
format = "[$symbol]($style) "

[os.symbols]
Macos = "îœ‘"
Debian = "î½"
NixOS = "ïŒ“"

[directory]
style = "cyan"
format = "[$path]($style)[$read_only]($read_only_style) "
read_only = " ó°Œ¾"
read_only_style = "bold red"
truncate_to_repo = true
truncation_length = 1
truncation_symbol = "î¾ "

[git_branch]
symbol = "î‚  "
style = "green"
format = "[$symbol$branch]($style) "

[git_state]
style = "blue"
format = "\\([$state( $progress_current/$progress_total)]($style)\\) "

[git_status]
style = "red"
format = "([$all_status$ahead_behind]($style) )"
conflicted = "ï‘§ "
untracked = "?"
modified = "!"
staged = "+"
ahead = "â‡¡"
behind = "â‡£"
diverged = "â‡•"

[status]
disabled = false
symbol = "ï‘§ "
style = "red"
format = "[$symbol$status]($style) "

[jobs]
symbol = "ï€“ "
style = "blue"
number_threshold = 1
format = "[$symbol$number]($style) "

[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](bold red)"
vimcmd_symbol = "[â®](bold blue)"

[cmd_duration]
min_time = 1500
style = "blue"
format = "[ó±«‘ $duration]($style) "

[time]
disabled = false
time_format = "%R"
style = "black"
format = "[ó°¥” $time]($style) "

[aws]
symbol = "ïƒ‚ "
style = "bold yellow"
format = "[($profile)(\\($region\\)) $symbol]($style) "

[docker_context]
symbol = "ïŒˆ "
style = "cyan"
format = "[$symbol$context]($style) "

[nix_shell]
symbol = "ïŒ“ "
style = "blue"
format = "[$symbol$state( \\($name\\))]($style) "

[nodejs]
symbol = "îœ˜ "
style = "green"
format = "[$symbol$version]($style) "
detect_files = ["package.json", "pnpm-lock.yaml", "pnpm-workspace.yaml", "yarn.lock", "package-lock.json"]
detect_extensions = ["js", "ts", "mjs", "cjs"]

[bun]
symbol = "î¯ "
style = "white"
format = "[$symbol$version]($style) "
detect_files = ["bun.lockb", "bun.lock"]

[python]
symbol = "î˜† "
style = "yellow"
format = "[$symbol$version( \\($virtualenv\\))]($style) "
detect_files = ["pyproject.toml", "uv.lock", "requirements.txt", ".python-version", "poetry.lock"]

[golang]
symbol = "î˜§ "
style = "cyan"
format = "[$symbol$version]($style) "
detect_files = ["go.mod"]

[rust]
symbol = "î¨ "
style = "red"
format = "[$symbol$version]($style) "
detect_files = ["Cargo.toml"]

[lua]
symbol = "î˜  "
style = "magenta"
format = "[$symbol$version]($style) "
detect_files = ["stylua.toml", ".luarc.json", ".luarc.jsonc"]

[c]
symbol = "î˜ "
style = "blue"
format = "[$symbol]($style) "
detect_extensions = ["c", "h", "hpp", "cpp"]
